import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import initializeApollo from "../lib/apollo";
import { gql, useQuery } from "@apollo/client";

//Client Side Query
const FETCH_USERS = gql`
  query fetchusers {
    users {
      id
      name
    }
  }
`;
export default function Home({ products }) {
  const { loading, error, data } = useQuery(FETCH_USERS);
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js and Hasura!</a>
        </h1>
        <ul>
          {products.map((products) => (
            <li key={products.id}>
              {products.name}---${products.price}
            </li>
          ))}
        </ul>
        {loading ? <div>loading....</div> : null}
        {error ? <div>Error....</div> : null}
        {data && data.users
          ? data.users.map((user) => {
              return <div key={user.id}>{user.name}</div>;
            })
          : null}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps(context) {
  /*
  const options = {
    method: "POST",
    headers: {
      "x-hasura-admin-secret":
        "ADMIN_SECRET",
    },
    body: JSON.stringify({
      query: `query fetchproduct{
        products{ 
          id
          name
          price
        }
      }`,
      operationName: "fetchproduct",
    }),
  };
  const fetchResponse = await fetch(
    "https://nextj-hasura.hasura.app/v1/graphql",
    options
  );
  const responseJson = await fetchResponse.json();
  console.log(responseJson);
  const products = responseJson.data.products;
  */
  const client = initializeApollo();
  // console.log(client);
  const { data } = await client.query({
    query: gql`
      query fetchproduct {
        products {
          id
          name
          price
        }
      }
    `,
  });
  console.log(data);
  return {
    props: {
      products: data.products, //products,
    }, // will be passed to the page component as props
  };
}
